apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: europe-southwest1-docker.pkg.dev/microservicesdotnet/microservices-repo/authservice:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: authservice-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - port: 80
    targetPort: 80
