// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 964, DateTimeKind.Utc).AddTicks(9173),
                            Description = "High-performance laptop with 16GB RAM and 512GB SSD",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/laptop.jpeg?updatedAt=1761677974008",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4811),
                            Description = "Ergonomic wireless mouse with precision tracking",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/mouse.jpg?updatedAt=1761677974066",
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4829),
                            Description = "RGB mechanical keyboard with blue switches",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/keyboard.jpg?updatedAt=1761677974064",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4833),
                            Description = "27-inch 4K UHD monitor with HDR support",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/monitor.png?updatedAt=1761677974086",
                            Name = "4K Monitor",
                            Price = 449.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4837),
                            Description = "7-in-1 USB-C hub with HDMI and ethernet ports",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/hub.webp?updatedAt=1761677974386",
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4840),
                            Description = "1080p HD webcam with built-in microphone",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/cam.webp?updatedAt=1761677974061",
                            Name = "Webcam HD",
                            Price = 69.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4843),
                            Description = "Noise-cancelling over-ear headphones",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/photo-1505740420928-5e560c06d30e_7tWlfCNAr.avif?updatedAt=1759220323847",
                            Name = "Headphones Pro",
                            Price = 199.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 27, 14, 5, 14, 965, DateTimeKind.Utc).AddTicks(4846),
                            Description = "Portable external SSD with USB 3.2 Gen 2",
                                ImageUrl = "https://ik.imagekit.io/MedHerak/products/ssd.jpg?updatedAt=1761677973996",
                            Name = "External SSD 1TB",
                            Price = 129.99m,
                            Stock = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
